spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    allow-circular-references: true
#  mvc:
#    cors:
#      allowed-origins: http://localhost
#      allowed-methods: GET,POST,PUT,DELETE
#      allow-credentials: true
#      max-age: 3600
  #  datasource:
#    hikari:
#      maria:
#        dirver-class-name: #{driver class name}
#        url: #{url}
#        username: #{username}
#        password: #{password}smartwcs1234

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
  port: 8080

# mybatis config
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations:
    - /mapper/**/*.xml